### ISSUE TITLE
Plugin not using system defaults when no frontmatter is in note

### ISSUE THREAD

**Issue by namtrah** [bwydoogh/obsidian-force-view-mode-of-note#27]
Just installed this and have one note in Live preview mode. Obsidian settings are defaulting to Live preview mode (with editor). When I change to another note, the default is "Source Mode". This is not what I want. It takes me two clicks to get back to Live Preview.

**Comment by bwydoogh** [comment]
Do you have the same problem as reported here (and watch the discussion): see https://github.com/bwydoogh/obsidian-force-view-mode-of-note/issues/25

**Comment by namtrah** [comment]
It still seems broken. I have turned on both flags in your settings. When I open my Home page which has set Reader Mode, then any page I open (newly) after that automatically is in reader as well. It is not in Live Preview as I would expect (and is set by default).

**Comment by namtrah** [comment]
I have confirmed that I can recreate this.

### Settings: 
**Editor**
- Default View for New Tabs:  "Editing View"
- Default Editing Mode:  "Live Preview"
**Force Note View Mode**
- Ignore opened files:  **ON**
- Ignore force view when not in front matter:  **ON**

1. Start Page.md contains `obsidianUIMode: preview` in front matter. No other file does.
2. Close all open Windows (CTRL-W)
3. Reload the application without saving (CTRL-P --> Reload the app)
4. Application automatically opens "Start Page.md" as I have the Homepage plugin. 
    1. It is in Reading mode as desired"
5. Open any other MD file
    1.  File is also in reading mode although 
        a) it does not have the flag in frontmatter, and 
        b) default settings are set to Live Preview.

I hope this helps. And yes, I think it is the same as #24 , but since he confirmed it to work. I am just continuing this note.

**Comment by bwydoogh** [comment]
Closing this issue, but if you feel that something is still not working as expected feel free to reopen the issue.

**Comment by Tom233-ai** [comment]
Not sure if it is the proper to respond or if I should have opened my own, but I am having a similar issue. 

I have a file that I have the ui preview mode in the yaml. When switching back to a note that I was editing, it goes into source instead of live preview mode. Live preview is my obsidian default. 

When I ignore force view when not in frontmatter, it keeps the same preview mode when switching to the non yaml document. 

I've tried both of the settings but how can I/is it possible to have a file with yaml for the ui preview mode, and then when switching to a file with no yaml have it go to my obsidian default- live preview, vs what is happening now- source mode.

Thanks
